keys:
  - &users:
    - &xamcost_elysium age17sf6nuth4fz4cs0etzdvt9gwa492wey08920h6k9dnj0xf5xqehq7s53l8
    - &xam_aeneas age165m3kj472xtfax2wanu7qhafyvaqt7k8udg96xgec6ue35lfvv8qwfts25
    - &maximecostalonga_xam_mac_m4 age1c3s8jmlgwrj4hw2xsyx0tgz68udnze08krdkej74s8g6ugygwfwscqpewj
  - &hosts:
    - &elysium age18snl3r4k6c7sz4t6q0m3hxvj4edlardyw90jv99v03cafynutycs3l8e5u
    - &aeneas age1yej8zjxq9x4yx72ent8czv3n5k4h635tv0gx23k269zwsnulydzqznx0hm
creation_rules:
  - path_regex: hosts/elysium/secrets.yaml$
    key_groups:
    - age:
      - *elysium
      - *xamcost_elysium
  - path_regex: hosts/aeneas/secrets.yaml$
    key_groups:
    - age:
      - *aeneas
      - *xam_aeneas
  - path_regex: home-manager/hosts/xam-mac-m4-secrets.yaml$
    key_groups:
    - age:
      - *maximecostalonga_xam_mac_m4
