{
  imports = [
    ./avante.nix
    ./bufferline.nix
    ./completion.nix
    ./conform.nix
    ./copilot.nix
    ./gitsigns.nix
    ./image.nix
    ./lsp.nix
    ./lualine.nix
    ./markdown-preview.nix
    ./mini.nix
    ./nvim-base64.nix
    ./neo-tree.nix
    ./obsidian.nix
    ./octo.nix
    ./oil.nix
    ./snacks.nix
    ./persistence.nix
    ./treesitter.nix
    ./trouble.nix
    ./ui.nix
    ./which-key.nix
  ];
}
