{
  imports = [
    ./avante.nix
    ./bufferline.nix
    ./completion.nix
    ./conform.nix
    ./copilot.nix
    ./gitsigns.nix
    ./image.nix
    ./lsp.nix
    ./lualine.nix
    ./markdown-preview.nix
    ./mini.nix
    ./neo-tree.nix
    ./obsidian.nix
    ./oil.nix
    ./snacks.nix
    ./persistence.nix
    ./telescope.nix
    ./treesitter.nix
    ./trouble.nix
    ./ui.nix
  ];
}
